// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsubtnJj-KStBWOd69g9plfYEpi6x_hb0',
    appId: '1:190000825551:web:1e9b61392efeba185263ba',
    messagingSenderId: '190000825551',
    projectId: 'instagram-tut-76d71',
    authDomain: 'instagram-tut-76d71.firebaseapp.com',
    storageBucket: 'instagram-tut-76d71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbd9EofHzRmqx9pwEl7z_u_DHdH7J-kc',
    appId: '1:190000825551:android:d717c69e63fa889c5263ba',
    messagingSenderId: '190000825551',
    projectId: 'instagram-tut-76d71',
    storageBucket: 'instagram-tut-76d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ikNTHi_KV90A-X8Ish3lmN_VWO-0lxI',
    appId: '1:190000825551:ios:25390f01b2be45465263ba',
    messagingSenderId: '190000825551',
    projectId: 'instagram-tut-76d71',
    storageBucket: 'instagram-tut-76d71.appspot.com',
    iosClientId: '190000825551-4k2trpkppft8gk5brmpp37tj0np29qr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ikNTHi_KV90A-X8Ish3lmN_VWO-0lxI',
    appId: '1:190000825551:ios:e31eb86b8734f66f5263ba',
    messagingSenderId: '190000825551',
    projectId: 'instagram-tut-76d71',
    storageBucket: 'instagram-tut-76d71.appspot.com',
    iosClientId: '190000825551-bep49kdichjeljl24g94ch07fgrt4h80.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
